### PR TITLE
Move hard-coded range values for Magic Trees into configurations.

### PR DESCRIPTION
**Pull request by noobanidus**
I've arbitrarily set minimums and maximums, although I don't believe these are too extreme. I've tested the sorting tree the most, as it's the easiest to test. All of the others appear to continue to function with their default values. 

Perhaps this has consequences that I'm unable to see, but at the very least having the ability to 
 enable/disable certain effects in the config is highly desirable.

Apologies if the indentation is wrong, my editor is playing up.

### CODE REVIEW

**Comment by bs2609** [comment]
The range values should be used as a radius, as that's what people will probably expect it to mean.
Also range comments for the config GUI tooltips aren't needed, that's already handled by default.

**Review by Drullkus — CHANGES_REQUESTED** [review]
What @bs2609 said

**Comment by noobanidus** [comment]
@Drullkus @bs2609 Apologies for the delay in getting back around to this. I believe the most recent commit (5a6377b) should resolve the issues you raised -- if I actually understood them properly! (It's entirely possible I misunderstood).

I did simplify the code which converted the ranges into BlockPos slightly as well, meaning that the algorithm (rand(32 + 1) / 16 -> rand(16 * 2 + 1) / 16) is now in one location instead of repeated multiple times.

I also halved the sorting tree range in the config and doubled it in the source code as well.

**Comment by Tamaized** [comment]
Sad to see that this didn't get the proper attention. Would you like to reimplement it in 1.18?

**Comment by GizmoTheMoonPig** [comment]
this was a very nice idea and would be perfect for the mod, so I went ahead and implemented it myself in d3c357ff3e68756b112b0b5ff9f5fae8c830a3e8. I'm sorry this PR never got pulled, but the feature got in regardless. Thank you for taking the time to make this!

**Pull request closed without merging**
