### PR TITLE
Fix incomplete hedge maze #2035

### PR DESCRIPTION
**Pull request by Sleepy-Horse**
Generation runs from one of the corner of the maze. If the corner is blocked by 3x3 rooms it can't generate in the most of the maze (before, maze from the issue):
temp
after:
temp0

another random example
before:
image
after:
temp0

Other solutions:
- Start generation from several points
- Reroll generation if 3x3 rooms break down maze into several connected components

### CODE REVIEW

**Comment by Tamaized** [comment]
i love how simple the fix was

**Review by Drullkus — APPROVED** [review]

**Comment by Sleepy-Horse** [comment]
Mazes generate a little more open with this change but I think it's ok

**Comment by GizmoTheMoonPig** [comment]
I'd like to do a little testing of how hedge makes look now with this change just to make 100% sure we're happy with it, but thank you for looking into this

**Comment by GizmoTheMoonPig** [comment]
So after doing a little comparing between the 2 versions, I think that this isn't the right fix for this. The main reason for this is because the maze no longer accounts for the big rooms when drawing the maze, it instead just slaps them on top of the already generated maze. This does lead to it being more open like you said, but it also creates a lot of unevenness and single pillar hedges which honestly don't look great. If there is a nicer way to incorporate the big rooms into generation instead of just slapping them in the already generated maze while also fixing the initial bug I would prefer that. 

I would not be opposed to the idea of generating less big rooms (maybe make it random instead of always being 5? Might be out of scope for this PR) and perhaps generating them in different quadrants in the maze instead of just in random spots. I would imagine any other fixes would require a little rewriting of the code, so if you don't think you can handle it I can add it our todo list for later (Drull has talked about rewriting the hedge maze code at some point so maybe its something he wants to do? Idk)

**Comment by Sleepy-Horse** [comment]
broken maze (after new fix):
image

random example:
image

**Review by GizmoTheMoonPig — APPROVED** [review]
Much happier with how this looks. I'll let other people look over the code as well but this gets a thumbs up from me

**Comment by jodlodi** [comment]
looks good to me :)

**Pull request merged**
