### PR TITLE
Additional loot tables as per #741

### PR DESCRIPTION
**Pull request by noobanidus**
I'm not sure that I haven't messed up. For the Tower Ghast, I'm
uncertain if it would by default automatically go to the Minecraft Ghast
loot table -- I didn't see anything that would override it.

Otherwise, where a loot table was not already previously specified or
assumed due to inheritance, a blank one was created.

Where there was an existing vanilla one, I copied the example of bunny.
Where there was an inheritance from a Twilight Forest entity, I copied
referenced that directly.

### CODE REVIEW

**Comment by noobanidus** [comment]
Also I did nothing with the goblin knight as it doesn't make sense for a multipart entity to have separate loot tables for each part if both parts die dependently.

**Review by williewillus — CHANGES_REQUESTED** [review]
couple things:
1. No need to have @Nullable on the methods if you're obviously returning something nonnull
2. iirc just `{}` will suffice for an empty loot table, no need for an empty pools array

looks good otherwise

**Comment by noobanidus** [comment]
All righty:

1. I just used IntelliJ's generate override which auto-added the @Nullable. I wasn't sure on the project standard so I left it in. Do you want me to remove the @Nullable?
2. I wasn't entirely sure myself, but I'll modify the tables accordingly.

**Comment by noobanidus** [comment]
Okay, those changes were made as was requested!

**Review by Tamaized — APPROVED** [review]

**Pull request merged**
