### PR TITLE
Update ja_jp.json

### PR DESCRIPTION
**Pull request by koh-gh**
Based on the translation for 1.12.2, tweaked some and added translations for new contents.

### CODE REVIEW

**Review by GizmoTheMoonPig — APPROVED** [review]
Looks good to me! All I would say is that the comment I made at the top isnt really needed anymore, but thats not super important. I'll let someone else on the team review as well, since ive never really done PR reviews before.

**Comment by koh-gh** [comment]
One month has passed, so I updated the language file.

**Comment by koh-gh** [comment]
Updated to the latest.

**Comment by GizmoTheMoonPig** [comment]
theres a file conflict since we had to fix a certain language key, so if you can fix this, we'll merge this

**Comment by koh-gh** [comment]
OK. Please wait for a while.

**Comment by koh-gh** [comment]
The conflict has been resolved. But I want to make a final confirmation, so please wait a little longer.

**Comment by koh-gh** [comment]
There seems to be no problem, so please merge.

**Pull request merged**
