### PR TITLE
Charm of Keeping fix with mods like PlayerRevive

### PR DESCRIPTION
**Pull request by Silvertide7**
Mods like PlayerRevive stop players from dying and create a down but not out state. Their events also subscribe to the death event on `HIGHEST`. When entering this state with a Twilight Forest charm of keeping your items are sometimes taken because this event is fired but you never actually die. The next time you do die and respawn your items are put into your inventory from the player data. This will hopefully allow some room for mods to interfere before the charm of keeping takes effect.

It appears this should also fix the keepCurios method as that checks for the existence of the inventory in the player data. Since this would never have the charm of keeping trigger that shouldn't either.

### CODE REVIEW

**Comment by GizmoTheMoonPig** [comment]
merge conflicts need fixing but I think this should be fine after thats done

**Comment by Silvertide7** [comment]
> merge conflicts need fixing but I think this should be fine after thats done

Sorry it took so long, conflicts resolved whenever you're ready to merge!

**Comment by Tamaized** [comment]
Er wait, I just realized this was targeting the 1.20 branch

**Comment by Tamaized** [comment]
I've cherry picked the commit into the 1.21 branch :slightly_smiling_face:

**Pull request merged**
