### PR TITLE
Solve #425 as originally intended

### PR DESCRIPTION
**Pull request by yrsegal**
This causes lightning to damage entities around the fake bolt, but not to start fires if the config is off.

The price in blood will be paid, as requested.

### CODE REVIEW

**Comment by yrsegal** [comment]
@Scorch-Mechanic, this is for you. :D

**Comment by Scorch-Mechanic** [comment]
Thank you.

**Comment by liach** [comment]
Funny that drull merges a pull without actual reviews

**Comment by Drullkus** [comment]
It looked good to me and I looked at the code already. Post-commit fixing was easy anyway.

**Pull request merged**
