### PR TITLE
Update zh_cn.lang

### PR DESCRIPTION
**Pull request by 3TUSK**
Ignore the commit message `Update zh_CN.lang`; the file name is unchanged.

@TartaricAcid

### CODE REVIEW

**Comment by Drullkus** [comment]
Old habits with the capitals in the lang, eh? :(

Do you have a Discord account? I'd love you and your teammates to come hang out. :D

**Comment by 3TUSK** [comment]
Yeah, old habits, plus those who stick with `"format": 2`.

And for Discord, I actually prefer IRC channel.

**Comment by 3TUSK** [comment]
uh, I forget that some of my friends do use Discord tho... like the one I mentioned above (@TartaricAcid).

**Comment by Drullkus** [comment]
Cool, feel free to join us and stay, you can access our discord with this invite: https://discord.gg/6v3z26B (Also in the Repo `README.md`) :D

**Review by liach — APPROVED** [review]

**Comment by 3TUSK** [comment]
*beep boop*

> This message is here to show that I have seen this message:
image

**Comment by Tamaized** [comment]
Am told this is ready to finally be merged :tada:

**Pull request merged**
