### PR TITLE
Door item texture fixes plus misc additions and fixes

### PR DESCRIPTION
**Pull request by xemnes**
-Fixed missing door item textures
-added custom transwood door textures
-added some missing english localization

### CODE REVIEW

**Comment by GizmoTheMoonPig** [comment]
1.12 will no longer be seeing updates, as we've moved on to more recent versions. We also had our own idea for door item models that make them different than the vanilla ones, they just haven't been made yet. We will get to them eventually, but more important tasks loom ahead of us when it comes to this mod. Thank you for being one of the few people to actually go out and attempt this yourself, its really cool seeing people do this even if it wont get accepted in the end sadly.

**Comment by xemnes** [comment]
thats fine, its here regardless if anyone wants to build it themselves anyway.

**Comment by Drullkus** [comment]
For missing textures on an EoL version, a Resource pack would be easier to distribute than a custom build.

If you’re not familiar with Resource-Packing for a mod, it’s basically the same thing as a regular for the core Minecraft assets except you use the `twilightforest` namespace.

I got confidence you’ll know what to do. Lemme know if you get hung on any problems

**Comment by xemnes** [comment]
oh i can make a resource pack, the problem is, i had to change a bit of code because no matter what i tried to get the model and texture to work, it wouldnt. it turned out that something wasnt registering the item texture, the class i added caused it to work.

**Comment by Weedoof** [comment]
Out of curiosity, would this PR be considered if it was ported to the 1.17.x branch? Just curious since I'd love to use these textures for a small modpack I'm working on, so porting them wouldn't be any trouble at all for me - I actually made the fork already, but I registered that I should probably ask before I go and open a new PR. The only issue is that the transwood door block isn't set to support transparency, which would need to be changed for a resource pack to work fully with xemnes's textures as they are now.

**Comment by Tamaized** [comment]
No because we already have an artist jabba-fying all our blocks and making those as well

Not to mention the code section isn't needed anymore post 1.13

**Comment by PaulEvans2024** [comment]
> -Fixed missing door item textures -added custom transwood door textures -added some missing english localization



> -Fixed missing door item textures -added custom transwood door textures -added some missing english localization

Hello, maybe you have a compiled mod file, because I can't compile the Gradle project, errors occur, I would be very grateful.

If you are interested in what problems, then below I described the essence in detail:

I need to compile the project in Gradle, but when I try to Build, I get an error with SSL certificates before downloading files from the Maven repository, since an error occurs, it accordingly does not even get to downloading those same dependencies, and of course, in this scenario, it is not possible to compile the project into .jar and in it create .class files from .java files. I would appreciate your help. And also in this project, not all links to dependencies work, some are no longer available, and I don’t have the skills to replace them with others and generally find others.

**Comment by ghost** [comment]
> > -Fixed missing door item textures -added custom transwood door textures -added some missing english localization
> 
> > -Fixed missing door item textures -added custom transwood door textures -added some missing english localization
> 
> Hello, maybe you have a compiled mod file, because I can't compile the Gradle project, errors occur, I would be very grateful.
> 
> If you are interested in what problems, then below I described the essence in detail:
> 
> I need to compile the project in Gradle, but when I try to Build, I get an error with SSL certificates before downloading files from the Maven repository, since an error occurs, it accordingly does not even get to downloading those same dependencies, and of course, in this scenario, it is not possible to compile the project into .jar and in it create .class files from .java files. I would appreciate your help. And also in this project, not all links to dependencies work, some are no longer available, and I don’t have the skills to replace them with others and generally find others.

I fixed the version 1.12.2 build with this fix.
[Ready to build code](https://github.com/rustzzdevel/twilightforest/tree/1.12.x-door_fix%2Bmisc)
[Download release](https://github.com/rustzzdevel/twilightforest/releases/tag/1.12.x-door_fix%2Bmisc)

**Pull request closed without merging**
