### PR TITLE
fixed bird take off sound

### PR DESCRIPTION
**Pull request by Tamaized**
not quite sure why this was a thing but ok

### CODE REVIEW

**Comment by williewillus** [comment]
Can you find out what they were originally? The event numbers changed between 1.7 and 1.10, but there's definitely supposed to be something there. Bat sound maybe?

**Comment by Tamaized** [comment]
I'll look around when I can later today, and update it if needed

**Comment by Tamaized** [comment]
Dug through the 1.7 code and it did indeed map to 'mob.bat.takeoff', updated as so.

**Comment by williewillus** [comment]
Excellent, thanks!

**Pull request merged**
