### PR TITLE
Replace umlaut-o with plain o. Resolves build/compilation issues.

### PR DESCRIPTION
**Pull request by noobanidus**
There is literally no reason why I should be getting an error trying to
build the project, rebuild the project or reload classes. While the
Gradle settings have it compiling correctly, for whatever reason I'm
unable to build or rebuild the project/reload classes after launching
because of this umlaut.

I have changed my own encoding settings multiple times to no avail,
as they always seem to reset when switching between projects. I end
up spending more time fixing my build environment than doing actual
coding.

Having to change the actual source code and then make sure I don't
accidentally include it in any commits is a little bit frustrating.

### CODE REVIEW

**Comment by 3TUSK** [comment]
Isn't this just an issue with system default charset encoding?
```groovy
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
```

**Comment by noobanidus** [comment]
My point is more along the lines that it would be nice if it just worked out of the box without having to change defaults.

**Comment by 3TUSK** [comment]
That's why I suggest to enforce an encoding in `build.gradle` - yes that snippet I posted above goes into `build.gradle`. Many of projects I involved in has that to prevent non-English comments becoming gibberish when on a different operating system.

**Comment by bs2609** [comment]
@3TUSK:
https://github.com/TeamTwilight/twilightforest/blob/69bdf67d71a60c195139d601e7f2bdd1449c7522/build.gradle#L94-L96

I think their issue is getting it to work in IntelliJ out-of-the-box, although it seems to work fine there for me.

**Comment by noobanidus** [comment]
Well, I'm using IntelliJ/JetBrains out-of-the-box on Windows 10 with English (US/AU) as the default. I haven't changed any configuration settings and until this commit the only other issue that I had was with the symbols used in plotting out the, but that was a complaint from the compiler about the code-page being used.

I've tried a variety of different settings and options but so far the only one I've been able to get JetBrains to compile with is changing the name of the variable.

While I love this project and I want to contribute as much as I can, it's frustrating that I can't work with it without having to jump through a lot of hoops just to get it to **compile**.

**Comment by williewillus** [comment]
no point in losing sleep/precious time over this

**Pull request merged**
