### PR TITLE
fixed Ur-Ghast tear impact effects

### LINKED ISSUE #108: Urghast tears missing an animation when they hit the ground
Before, there was a breaking animation when they hit the ground, giving a better indication (?) that they were dangerous.

### PR DESCRIPTION
**Pull request by Tamaized**
This fixes #108

### CODE REVIEW

**Comment by williewillus** [comment]
interesting, why does the first call not work? 0.o

**Comment by Tamaized** [comment]
Unsure, I recall having to use the effect renderer in other mods due to the same issue. Could be worth looking into.

**Comment by Benimatic** [comment]
Huh, that's weird. The cause seems to be that when the urghast calls TwilightForestMod.proxy.spawnParticle(this.world, TFParticleType.BOSS_TEAR etc. that the world passed in is the server-side world, but somehow it gets passed to the client-side proxy? I don't totally get why that's happening. Changing the world in the client proxy particle method, say with a world = this.getClientWorld(); also fixes this bug.

**Comment by williewillus** [comment]
proxies are instantiated based on physical side, not logical side, so if you hit "Minecraft Client" in the IDE you're going to get a clientproxy regardless of the fact that you have an integrated server running in SP

**Comment by Benimatic** [comment]
I wondered if something like that was happening. I'm closing this one, as 6ffc8b00f98317baf4326146d7b057e4853b1ab5 addresses this. Thanks for helping us track down the problem, Tama!

**Pull request closed without merging**
