### PR TITLE
Ice crystals and ice cores will melt if they are in hot biomes

### PR DESCRIPTION
**Pull request by ghost**
Implemented Ice crystals and ice cores's melt future

Original issue↓
https://github.com/TeamTwilight/twilightforest/issues/302

### CODE REVIEW

**Comment by Tamaized** [comment]
What's with all the formatting changes

**Comment by ghost** [comment]
uh... sorry 
it seems that writing of my import was bad

**Comment by ghost** [comment]
import format changed

**Comment by Tamaized** [comment]
What about the rest of the formatting

**Comment by ghost** [comment]
finaly I was able to adjust the format

**Review by Drullkus — APPROVED** [review]

**Pull request closed without merging**
