### PR TITLE
update ja_jp.lang

### PR DESCRIPTION
**Pull request by koh-gh**

### CODE REVIEW

**Comment by Tamaized** [comment]
Just confirming here, this is all good to go?

**Comment by koh-gh** [comment]
OK. This is all. Please forgive me that I am not used to using github.

**Comment by Tamaized** [comment]
Oh no nothing to be sorry about, I just wanted to make sure you had gotten all your changes in as we had changed more with the en_us lang while this PR was open.

**Comment by koh-gh** [comment]
I understood the meaning, thank you. I have a question. Does phantom armors' tooltip mean soulbound of thermal series or tinkers'?

**Comment by Tamaized** [comment]
It's a soulbound that never goes away even on death. Can die as many times as you want and the armors will stay with you every time.

**Comment by koh-gh** [comment]
Thank you. I took in all latest update of en_us.lang. Is shieldParryTicksBeam's text OK?(It's ???)

**Comment by Tamaized** [comment]
I'm guessing @Drullkus want's it to be a bit of a secret to the player? Not entirely sure myself lol.

**Comment by koh-gh** [comment]
I see. Please merge.

**Pull request merged**
