### PR TITLE
Auroraplace EntityTweek and some bugfix

### PR DESCRIPTION
**Pull request by ghost**
changed detail:
when iceshooter and ice exploder is hot biome,they melt
Fixed a bug that ice queen did not hover when attacked by enemies other than player

### CODE REVIEW

**Comment by Tamaized** [comment]
Perhaps we should do a base class for the ice mobs to reduce duplicate code

**Comment by ghost** [comment]
I add IceEntityBaseClass!
It should be compact now

**Comment by Tamaized** [comment]
For the sake of consistency, let's go with EntityTFIceMob

**Comment by pentantan** [comment]
rename finished

**Review by Tamaized — APPROVED** [review]

**Pull request merged**
