### PR TITLE
Initial support to allow skylight to be disabled via config

### PR DESCRIPTION
**Pull request by bs2609**
Posting this so people can take a look.

Not yet exposed in the config, needs to be set manually. The current lightmap implementation is also mostly there to serve as a starting point.

Lighting updates, _especially_ for skylight, is pretty much the biggest consumer of worldgen time at present. As a result, this setting makes a significant difference to worldgen performance, although with obvious tradeoffs.

For this, trying it out is probably the best way to get a good idea. Note that this option is effectively permanent per-world (it's persisted to the level save), ~~as chunks saved with skylight off can't be loaded with skylight on~~.

**Edit:** Vanilla actually writes dummy skylight data to the save regardless, so this is less of an issue than I initially thought.

### CODE REVIEW

**Comment by Drullkus** [comment]
Why set it chunk-persistent? Config settings can be set so they require a world reload.

**Comment by bs2609** [comment]
Going from skylight -> no skylight is fine, but the reverse doesn't really work well - all existing chunks will have zero skylight, and you can't really get it back easily or reliably. It won't crash but it's still not very good.

**Comment by Drullkus** [comment]
Ouch. Hm. Ok. I guess we can note this in the config setting.

**Comment by bs2609** [comment]
Persisting the config setting in the save file has been left disabled for now, will see what people think and make a decision later.

**Pull request merged**
