### PR TITLE
Bugfix: add durability to armors

### PR DESCRIPTION
**Pull request by Sleepy-Horse**
Before:
image
After:
image

### CODE REVIEW

**Comment by GizmoTheMoonPig** [comment]
dammit, I knew I forgot those. Once I confirm the values match the old ones i'll pull this

**Review by GizmoTheMoonPig — APPROVED** [review]
values look good! I assume using the armor material directly (using `MATERIAL.getDurability`) doesnt work? I dont know what the registry ordering is for the armor materials so it may not work

**Comment by Sleepy-Horse** [comment]
I couldn't find MATERIAL.getDurability; moreover, I couldn't find any code containing these constants. Could you please send a link to it if it exists?

**Comment by GizmoTheMoonPig** [comment]
According to https://github.com/neoforged/NeoForge/pull/910, armor materials fire after items, meaning it wont currently work. Once that PR is pulled, you can use the armor material instead of hardcoding the numbers (`TFArmorMaterials.FIERY.get().getDurability(25)`). The numbers youll need to use for the multiplier are as follows:
Naga - 21
Ironwood - 20
Fiery - 25
Steeleaf - 10
Knightmetal - 20
Phantom - 30
Yeti - 20
Arctic - 10

**Comment by Sleepy-Horse** [comment]
It is still hardcoded like in vanilla. I believe `ArmorMaterial` doesn't contain durability values (unlike tool `Tier`). My suggestions to avoid hardcoding it in every piece of armor are:
- Create enum of durabilities for each ArmorMaterial
- Create a TFArmorMaterial, which has durability

**Comment by GizmoTheMoonPig** [comment]
alright, I had things mixed up now that I actually can look at the code (this is the first day all week that ive been able to sit down and actually do stuff). What you did here works for me. Sorry about the confusion!

**Pull request merged**
