### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by Telezhka-the-First**

### CODE REVIEW

**Comment by Telezhka-the-First** [comment]
Added missing lines, unified different versions of translation of one thing and translated a couple of lines

**Review by GizmoTheMoonPig — CHANGES_REQUESTED** [review]
Please don't add missing strings if they aren't localized, crowdin will just delete them if the file gets pulled. 
If you're going to translate a line, please translate the entire line. All of the banister and wall sign lines are half translated and I would prefer not to have that.

**Comment by Tamaized** [comment]
Merge conflicts

**Comment by Tamaized** [comment]
@GizmoTheMoonPig Does this look okay?

**Comment by Tamaized** [comment]
Also 1.19 target? @GizmoTheMoonPig

**Comment by GizmoTheMoonPig** [comment]
Really sorry we cant get this merged, its conflicting a lot with the current branch and I dont know which iterations of the translations to keep. Most of the file has already been translated via our [Crowdin page](https://crowdin.com/project/twilight-forest) and translations are handled much better over there. I dont always have time to review PRs so things like this will sometimes happen, sorry. Thank you for your work though!

**Pull request closed without merging**
