### PR TITLE
Bugfix: portals could destroy bedrock or teleport into the void

### PR DESCRIPTION
**Pull request by Sleepy-Horse**
Portals could break bedrock or teleport into the void. I fixed it.
Before:
Broke bedrock

After:
image
image
image

Before:
Teleported into the void
image

After:
image

### CODE REVIEW

**Comment by GizmoTheMoonPig** [comment]
The bottom of the portal can be any block (it doesnt need to be dirt) so if you could make the portal flush with the ground in that second screenshot case that would be lovely. Just generate the dirt if needed

This is more of a personal preference than anything but its still a change I think other people would be fine with too

**Comment by Sleepy-Horse** [comment]
Technically, it works, but it doesn't fit into existing holes and create portals on leaves. Is it a bug or a feature?
temp
image

**Review by GizmoTheMoonPig — APPROVED** [review]
looks good! Wont merge until someone else has a look as well but it works for me

**Comment by jodlodi** [comment]
to add input: seems good to me as well, probably safe bet to merge

**Pull request merged**
