### PR TITLE
Add Japanese translation lang file for branch 1.11.x

### PR DESCRIPTION
**Pull request by ghost**
I'm sorry.
Retry #152

### CODE REVIEW

**Comment by jambonmcyeah** [comment]
But the 1.11.x branch is no longer supported, there will be no 1.11.x releases.

**Comment by ghost** [comment]
OOPS...
Can you include **a part(valid)** ja_jp.lang in branch 1.12.x ?

**Comment by jambonmcyeah** [comment]
You could translate from the english lang file:
https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/resources/assets/twilightforest/lang/en_us.lang

**Comment by williewillus** [comment]
I cherry-picked this into 1.12.x

**Pull request closed without merging**
